# Generated by Django 3.2.4 on 2021-06-22 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, verbose_name='Tipo')),
                ('ano_de_fabricacao', models.IntegerField(verbose_name='Ano de Fabricação')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('cor', models.CharField(max_length=100, verbose_name='Cor')),
            ],
            options={
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='Garagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='None', max_length=100, verbose_name='Garagem')),
                ('consumidor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pessoa.pessoa')),
                ('veiculos', models.ManyToManyField(to='garagem.Veiculo')),
            ],
            options={
                'db_table': 'garagem',
            },
        ),
    ]
